---
- hosts: localhost
  become: true
  vars_files: vars.yaml
  tasks:
    - name: Registro de IP
      shell: hostname -I | awk '{print $1}'
      register: hip
    
    # CONFIGURING OS PERMISSIONS
    - name: Setting Setenforce
      shell: sudo sed -i.bkp '7c\SELINUX=permissive' /etc/selinux/config

    - name: Instalando Firewalld
      become: true
      shell: sudo yum install firewalld -y

    - name: Start Firewalld
      become: true
      shell: sudo systemctl start firewalld

    - name: Enable Firewalld
      become: true
      shell: sudo systemctl enable firewalld

    #- name: Configurando Firewall
    #  become: true
    #  shell: sudo firewall-cmd --add-service={http,https} --permanent

    - name: Open port
      become: firewall-cmd --add-port={10051/tcp,10050/tcp} --permanent

    - name: Reaload Firewall
      become: true
      shell: sudo  firewall-cmd --reload

    # INSTALANDO BANCO DE DADOS
    - name: Installing Mariadb
      shell: sudo dnf install mariadb-server
    
    - name: Starting Mariadb
      shell: sudo systemctl start mariadb
    
    - name: Starting Mariadb
      shell: sudo systemctl enable mariadb
    
    # INSTALANDO ZABBIX PROXY
    - name: Adicionando Repo Zabbix 6.0
      become: true
      shell: sudo rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/$(rpm -E %{rhel})/x86_64/zabbix-release-6.0-1.el$(rpm -E %{rhel}).noarch.rpm
      ignore_errors: yes

    - name: Update repos
      shell: sudo yum update -y

    - name: Instalando Zabbix Agent
      shell: sudo yum -y install zabbix-proxy-mysql zabbix-sql-scripts

    - name: Instalando Pip
      become: true
      shell: yum install python3-pip -y

    - name: Creating DB
      become: true
      shell: mysql -uroot -e "create database {{ db_name }} character set utf8mb4 collate utf8mb4_bin;"

    - name: Creating DB User
      become: true
      shell: mysql -uroot -e "create user {{ db_user }}@localhost identified by '{{ db_password }}';"

    - name: DbUser Priveleges
      become: true
      shell: mysql -uroot -e "grant all privileges on {{ db_name }}.* to {{ db_user }}@localhost;"

    - name: Refresh DB
      shell: mysql -uroot -e "flush privileges;"
    
    - name: Importing DB Schema
      become: true
      shell: cat /usr/share/doc/zabbix-sql-scripts/mysql/proxy.sql | mysql -u{{ db_user }} -p {{ db_name }}

    - name: Adding Proxy Mode
      become: true
      shell: sed -i.bkp '13c\ProxyMode={{ proxymode }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding ConfigFrequency
      become: true
      shell: sed -i.bkp '14c\ConfigFrequency={{ ConfigFrequency }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding Server
      become: true
      shell: sed -i.bkp '32c\Server={{ server }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding Hostname
      become: true
      shell: sed -i.bkp '42c\Hostname={{ proxy_name }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding DbName
      become: true
      shell: sed -i.bkp '171c\DBName={{ db_name }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding DBUser
      become: true
      shell: sed -i.bkp '186c\DBUser={{ db_user }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding DBPassword
      become: true
      shell: sed -i.bkp '194c\DBPassword={{ db_password }}' /etc/zabbix/zabbix_proxy.conf

    - name: Adding DBAllow #for supporting mysql5.0
      become: true
      shell: sed -i.bkp '219c\AllowUnsupportedDBVersions=1' /etc/zabbix/zabbix_proxy.conf

    - name: Restartar Service
      become: true
      shell: systemctl restart zabbix-proxy

    - name: Habilitar Service
      become: true
      shell: systemctl enable zabbix-proxy
    
    - name: Install Zabbix-api
      become: true
      shell: pip3 install zabbix-api

    - name: Criando Proxy no Server
      ignore_errors: yes
      local_action:
        module: zabbix_proxy
        server_url: "{{ urlserver }}"
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        proxy_name: "{{ proxy_name }}"
        #description: ExampleProxy
        status: active # active or passive
        state: present
        timeout: 10
        interface:
            type: 0
            main: 1
            useip: 1
            ip: "{{ hip.stdout }}"
            dns: ""
            port: 10050